services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: pet_symptom_tracker_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - pet_symptom_tracker
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - pet_symptom_tracker
    restart: unless-stopped

networks:
  pet_symptom_tracker:
    driver: bridge

volumes:
  postgres:
    driver: local
